language: node_js
node_js:
  - stable

#before_install:
#  - git config --global user.email "travis@travis-ci.org"
#  - git config --global user.name "Travis CI"
script:
  - npm run build
after_success:
  - SOURCE_BRANCH="master"
  - TARGET_BRANCH="gh-pages"
  - SOURCE_DIR=${PWD##*/}
  - TARGET_DIR=$TARGET_BRANCH
  - REPO=`git config remote.origin.url`
  - PROJECT=`echo $REPO | sed 's/.*github.com//' | sed -e 's/^[//]*//' | sed -e 's/^[:]*//'`

  # Clone my repo one folder up for gh-pages version
  - cd ..
  - git clone $REPO $TARGET_DIR --branch $TARGET_BRANCH --single-branch --depth 1
  - cd $TARGET_DIR

  # set remote on gh-pages version

  # clean (remove unchecked in files) gh-page version
  - git clean -f -d

  # fetch and Checkout gh-page branch
  - git pull origin

  # remove existing files
  - rm -rf ./*

  # copy files from dist to gh-page branch
  - cp -R ../$SOURCE_DIR/dist/* ../$TARGET_DIR

  - cat ./index.html >> ./404.html

  # setup user
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"

  # set github access token
  - git config github.token $github_token

  # Add files
  - git add .

  # commit changes
  - git commit -m "Travis Deploy, travis build $TRAVIS_BUILD_NUMBER"

  # push
  - git push https://$GITHUB_API_KEY@github.com/$PROJECT $TARGET_BRANCH

env:
  global:
    secure: "M4ktU4t4KJawO8Jthtf7n2yFmHcuCosmM+jv83/mPJdq5sAh0sqPNy9qBH3ZPUpndWugwRyK+wa/thYMBkwUUuRb/FQ5XiCaMYXJwBIb8M3+ADOjFkb7Acp7YH6mYGmroCBeIoZ2DXVxja2Un+K2cWjS2eAnBRDco33RS/B/LVmM8/kJqtrrednwMROMayW8Mkbwma/ydMNAkNUUEz78UX3tp9O/dVf7ZIgEfa77FhWH7V4ypPZsfEfMlx9ROUh3Go1JJKQnQjtz95w7PmupNTkSAuH5Dkr/3FE3F+GvIHtUlyTO1JwxUJEm+29Sd9RJCbP33eSKdmA8HChM0wvxwAWK9CnJuNcvRopWMQUSt/H77aoV0eluAhcv87GRa75ywv/tEgm+mrFMfBabnc2pGZaqkGFHfQ+ZYsxYxBeccr1yYiU8+t+qhPYGsqagyjTPVB2eJjk8kp68VVrWR+p4X+KJiTD0P6PrJoemGfb9pPms7jptA+J2xEeNbbLlYv3X6KP/1wLR9qFbisgzncC7+57onnktwzzOrsfZGDaxdWupKwUdIJbOXHQfOscCDWPfoOH0vuVRaiaaeUCChw0kow3M2Guo3ylTrjNElb8FL83vAIvAXeSFECVVRZlPXOvyYANRHVnkLHTvG+l9vNiwt27Lq/9SM1tIXmy1b6Pw6pI="

